name: Deploy to Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --production

      - name: Zip Application
        run: zip -r function.zip . -x "node_modules/*" ".github/*"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: my-node-api
          package: function.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
